name: 09 using functions

on: 
    workflow_dispatch:  

jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Print PR title
              run: echo "${{ github.event.pull_request.title }}"

            - name: Print PR Lables
              run: |
                cat << EOF
                ${{ toJson(github.event.pull_request.labels )}}
                EOF

            - name: Bug step
              if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix') }}
              run: echo "I am a bug fix"

            - name: i will be execute
              if: ${{ success() }}
              run: echo "i will print if previous steps succeed"

            - name: i will skipped
              if: ${{ failure() }}
              run: echo "i will print if previous steps failed"

            - name: i will be execute
              if: ${{ !cancelled() }}
              run: echo "i will always print except whrn the workflow cancelled"

            - name: i will execute when cancelled
              if: ${{ cancelled() }}
              run: echo "i will print if the workflow has been cancelled"
              