name: 11 - working with Inputs

on: 
  workflow_dispatch:
    inputs:
    
      dry-run:
        #input type-1
        type: boolean
        description: skip deployment and only print build output
        default: false

      target:
        #input tpe-2
        type: environment
        required: true
        description: which environment the workflow will target
    
      tag:
        #input type-3
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v3
        description: Release from which to build and deploy



jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "building from Tag ${{ inputs.tag }}"

  Deploy:
    runs-on: ubuntu-latest
    if: ${{ !inputs.dry-run}}
    environment: ${{ inputs.target }}
    needs: Build
    steps:
      - name: Deploy
        run: echo "deploying to ${{ inputs.target}}"
  
